---
# Tasks for the Task runner:
#
# https://taskfile.dev/

version: "3.50"

set: [pipefail]

includes:
  copier:
    taskfile: tasks/copier
  hooks:
    taskfile: tasks/vcs-hooks
    optional: true

tasks:
  default:
    cmds:
      - task: "list"

  list:
    desc: List available tasks
    cmds:
      - "{{.TASK_EXE}} --list"
