---
# Maintained by Copier: NEVER EDIT THIS FILE
#
# See:
#
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually

_commit: v0.5.0
_src_path: git@gitlab.com:stuartellis-org/templates/copier-sve-prelude.git
copyright_date: '2026'
copyright_holder: Stuart Ellis
copyright_holder_email: stuart@stuartellis.name
maintainer_email: stuart@stuartellis.name
maintainer_fullname: Stuart Ellis
maintainer_username: sjellis
project_description: A Copier template that provides project tooling for consuming
    Copier templates
project_name: copier-sve-prelude
repository_name: copier-sve-prelude
repository_namespace: stuartellis-org/templates
repository_provider: gitlab.com
