---
# Tasks for
#
# - https://taskfile.dev/

version: "3.50"

set: [pipefail]

vars:
  PRELUDE_COPIER_ANSWERS_FILE: ".copier/.copier-answers-sve-prelude.yaml"
  TASK_INCLUSIONS_INDEX_DIR: "./tasks/plumbing/managed"
  TASK_INCLUSIONS_ROOT_DIR: "./tasks/managed"

tasks:
  register:tasks:
    desc: "Register managed tasks"
    summary: |
      Generates the Taskfile TASK_INCLUSIONS_INDEX_FILE.

      This Taskfile includes the subdirectories in TASK_INCLUSIONS_ROOT_DIR.
    aliases:
      - register
    silent: true
    cmds:
      - "mkdir -p {{.TASK_INCLUSIONS_INDEX_DIR}}"
      - "rm -f {{.TASK_INCLUSIONS_INDEX_FILE}}"
      - for: ["---", 'version: "3.50"', "", "includes:"]
        cmd: "echo '{{.ITEM}}' >> {{.TASK_INCLUSIONS_INDEX_FILE}}"
      - for: { var: TASK_INCLUSIONS_DIRS }
        cmd: |
          echo '  {{.ITEM}}:' >> {{.TASK_INCLUSIONS_INDEX_FILE}} &&
          echo '    taskfile: ../../{{.TASK_INCLUSIONS_BASE_DIR}}/{{.ITEM}}' >> {{.TASK_INCLUSIONS_INDEX_FILE}}
          echo '    optional: true' >> {{.TASK_INCLUSIONS_INDEX_FILE}}
          echo '' >> {{.TASK_INCLUSIONS_INDEX_FILE}
    vars:
      TASK_INCLUSIONS_BASE_DIR:
        ref: "base .TASK_INCLUSIONS_ROOT_DIR"
      TASK_INCLUSIONS_DIRS:
        sh: "ls {{.TASK_INCLUSIONS_ROOT_DIR}}"
      TASK_INCLUSIONS_INDEX_FILE: "{{.TASK_INCLUSIONS_INDEX_DIR}}/Taskfile.yaml"

  reset:
    desc: "Reset the current project"
    summary: |
      Reset the current project to the most recent Git commit.
      This prepares it for updates.
    cmds:
      - "git clean -fdx"
      - "git reset --hard HEAD"

  update:prelude:
    desc: "Update the prelude Copier template"
    summary: |
      Update the current project with the prelude Copier template.

      Use the answers file for the template, rather than prompt the user.
    cmds:
      - task: "copier:update:auto"
    vars:
      COPIER_ANSWERS_FILE: "{{.PRELUDE_COPIER_ANSWERS_FILE}}"
