---
# Tasks for the Copier tool
#
# - https://taskfile.dev/
# - https://copier.readthedocs.io/en/stable/
#
# Copier requires Git to function.
#
# Set these variables to override the defaults:
#   - COPIER_CMD
#   - COPIER_VERSION_ID

version: "3.50"

set: [pipefail]

vars:
  COPIER_VERSION_ID: "9.17.0"
  DEFAULT_COPIER_CMD: "pipx run copier=={{.COPIER_VERSION_ID}}"
  CURRENT_COPIER_CMD:
    ref: "default .DEFAULT_COPIER_CMD .COPIER_CMD"
  COPIER_PROJECT_ANSWER_DIR: ".copier"
  COPIER_PROJECT_ANSWER_FILES:
    sh: "ls {{.COPIER_ANSWERS_DIR}}/.copier-answers-*.*"

tasks:
  default:
    cmds:
      - task: "list"

  add:
    desc: "Add the specified Copier template to the project"
    aliases:
      - copy
    summary: |
      Add the Copier template specified by the URL to the current project.

      To avoid issues, use the Git SSH URL, rather than the HTTPS address.

      For example:
        task copier:add -- git@gitlab.com:group/my-copier-template.git
    cmds:
      - "{{.CURRENT_COPIER_CMD}} copy {{.CLI_ARGS}}"

  list:
    desc: "Lists the Copier answers files in the current project"
    summary: |
      Lists the Copier answers files for the current project
    silent: true
    cmds:
      - for: { var: COPIER_PROJECT_ANSWER_FILES }
        cmd: "echo {{.ITEM}}"

  run:*:
    desc: "Run a Copier subcommand with the specified arguments"
    summary: |
      Run a subcommand of Copier with the specified arguments.

      This uses Task argument forwarding.

      For example:
        task copier:run:copy -- git@gitlab.com:group/my-copier-template.git
    cmds:
      - "{{.CURRENT_COPIER_CMD}} {{.COPIER_SUB_CMD}} {{.CLI_ARGS}}"
    vars:
      COPIER_SUB_CMD: '{{index .MATCH 0}}'

  update:auto:
    desc: "Update a Copier template from an answers file with no inputs"
    summary: |
      Update the current project with one of the Copier templates that it uses.

      This only uses the answers file in the current project, with no other inputs.
      The URL of each template is stored by the answers file.

      To specify the relevant Copier answers file, set the variable COPIER_ANSWERS_FILE.

      For example:
        COPIER_ANSWERS_FILE=copier-answers-my-template.yaml task copier:update:auto
    requires:
      vars:
        - name: COPIER_ANSWERS_FILE
          enum:
            ref: .COPIER_PROJECT_ANSWER_FILES
    cmds:
      - "{{.CURRENT_COPIER_CMD}} update -A -a {{.COPIER_ANSWERS_FILE}}"
